# Generated by Django 4.2.9 on 2025-09-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20250909_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='graduation_college',
            field=models.CharField(blank=True, max_length=200, verbose_name='Graduation College'),
        ),
        migrations.AddField(
            model_name='lead',
            name='graduation_course',
            field=models.CharField(blank=True, max_length=200, verbose_name='Graduation Course'),
        ),
        migrations.AddField(
            model_name='lead',
            name='graduation_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3, verbose_name='Graduation Status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='Industry (Legacy)'),
        ),
    ]
