# Generated by Django 4.2.9 on 2025-09-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_lead_graduation_college_lead_graduation_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='course_interested',
            field=models.CharField(blank=True, max_length=200, verbose_name='Course Interested In'),
        ),
    ]
