# Generated by Django 4.2.9 on 2025-09-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_lead_course_interested'),
    ]

    # These fields are already added in previous migrations (0004 and 0005).
    # Keep this migration as a no-op to avoid duplicate column errors.
    operations = []
