# Generated by Django 4.2.9 on 2025-09-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_lead_course_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='graduation_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3, verbose_name='Graduation Status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='course_interested',
            field=models.CharField(blank=True, max_length=200, verbose_name='Course Interested In'),
        ),
    ]
