# Generated by Django 4.2.9 on 2025-09-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20250915_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
