# Generated by Django 4.2.9 on 2025-09-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20250915_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
