# Generated by Django 4.2.9 on 2025-09-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20250915_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='company',
            new_name='school_name',
        ),
    ]
