# Generated by Django 4.2.9 on 2025-09-15 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20250915_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_graduated',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3, verbose_name='Is Graduated'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='graduation_college',
            field=models.CharField(blank=True, db_column='college_name', default='Not Specified', max_length=200, verbose_name='Graduation College'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='graduation_course',
            field=models.CharField(blank=True, default='Not Specified', max_length=200, verbose_name='Graduation Course'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='School Name'),
        ),
    ]
