# Generated by Django 4.2.27 on 2026-02-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_notificationadmin_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
