# Generated by Django 4.2.27 on 2026-03-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_leadalternatephone_dataaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code e.g. NEW, CONTACTED', max_length=30, unique=True)),
                ('name', models.CharField(help_text="Display name e.g. 'New', 'Contacted'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='secondary', help_text='Bootstrap badge color class e.g. info, success, danger', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System statuses cannot be deleted')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Lead Statuses',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='action',
            field=models.CharField(choices=[('view_lead_detail', 'View lead detail'), ('list_my_leads', 'List my leads'), ('view_business_detail', 'View business detail'), ('reveal_phone', 'Reveal phone'), ('reveal_alternate_phone', 'Reveal alternate phone')], db_index=True, max_length=50),
        ),
    ]
