# Generated by Django 4.2.27 on 2026-03-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_seed_lead_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code e.g. CALL, EMAIL, MEETING', max_length=30, unique=True)),
                ('name', models.CharField(help_text="Display name e.g. 'Phone Call', 'Email'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-tasks', help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='info', help_text='Bootstrap badge color class', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System types cannot be deleted')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activity Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NextAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code e.g. CALLBACK, SEND_BROCHURE', max_length=30, unique=True)),
                ('name', models.CharField(help_text="Display name e.g. 'Callback', 'Send Brochure'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Next Actions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('PROPOSAL', 'Proposal Sent'), ('FOLLOW_UP', 'Visit'), ('TRANSFER', 'Lead Transfer'), ('NOTE', 'Note')], db_index=True, max_length=30),
        ),
    ]
