# Generated by Django 4.2.27 on 2026-03-18 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_seed_activity_types_next_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('VISITS', 'Complete Pending Visits'), ('ACTIVITIES', 'Complete Pending Activities'), ('STATUS_LEADS', 'Work on Leads by Status'), ('CUSTOM', 'Custom Target')], db_index=True, max_length=20)),
                ('target_date', models.DateField(db_index=True)),
                ('target_count', models.IntegerField(default=0, help_text='Number of items to complete (0 = all available)')),
                ('status_filter', models.CharField(blank=True, help_text='Lead status code to filter by (for STATUS_LEADS type)', max_length=30)),
                ('priority', models.IntegerField(default=0, help_text='Lower = higher priority. Visits=1, Activities=2, Status-based=by sort_order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='DailyTargetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=15)),
                ('completed_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='main_app.counsellor')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main_app.dailytarget')),
            ],
            options={
                'ordering': ['target__priority'],
                'unique_together': {('target', 'counsellor')},
            },
        ),
    ]
