# Generated by Django 4.2.27 on 2026-03-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_simplify_dailytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='can_delete',
            field=models.BooleanField(default=True, help_text='Can delete leads, activities, etc.'),
        ),
        migrations.AddField(
            model_name='admin',
            name='can_manage_settings',
            field=models.BooleanField(default=True, help_text='Can manage lead sources, statuses, activity types, etc.'),
        ),
        migrations.AddField(
            model_name='admin',
            name='can_view_counsellor_work',
            field=models.BooleanField(default=True, help_text='Can view counsellor work details'),
        ),
        migrations.AddField(
            model_name='admin',
            name='can_view_performance',
            field=models.BooleanField(default=True, help_text='Can view counsellor performance'),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_superadmin',
            field=models.BooleanField(default=True, help_text='Full access to everything'),
        ),
    ]
